version: '3.8'

services:
  nextui-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextui-build:latest
    container_name: nextui-builder
    volumes:
      - ./workspace:/root/workspace
      - ./skeleton:/root/skeleton
      - ./build:/root/build
    environment:
      - PLATFORM=${PLATFORM:-tg5040}
      - COMPILE_CORES=${COMPILE_CORES:-true}
    working_dir: /root/workspace
    command: /bin/bash
    stdin_open: true
    tty: true

  # Serviço para build automático
  nextui-auto-build:
    extends: nextui-build
    container_name: nextui-auto-builder
    command: /root/build.sh
    stdin_open: false
    tty: false

networks:
  default:
    driver: bridge
