#!/bin/sh

# NOTE: becomes .tmp_update/updater

INFO=`cat /proc/cpuinfo 2> /dev/null`
case $INFO in
*"TG5040"*|*"TG3040"*)
	PLATFORM="tg5040" # Trimui Smart Pro or Brick
	;;
esac

# fallback for tg5040 20240413 recovery firmware
# TODO: doublecheck interaction with tg3040
# might need/want to strings /usr/trimui/bin/MainUI during install/update
# and store platform in a text file
if [ -z "$PLATFORM" ] && [ -f /usr/trimui/bin/runtrimui.sh ]; then
	PLATFORM="tg5040"
fi

/mnt/SDCARD/.tmp_update/$PLATFORM.sh # &> /mnt/SDCARD/boot.txt

# force shutdown so nothing can modify the SD card
echo s > /proc/sysrq-trigger
echo u > /proc/sysrq-trigger
echo o > /proc/sysrq-trigger
