---
name: Development/Desktop

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  attestations: write
  contents: read
  id-token: write

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      PLATFORM: desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          brew install gcc make sdl2_image sdl2_ttf libzip libsamplerate
          sudo ./workspace/desktop/macos_create_gcc_symlinks.sh

      - name: Setup
        run: make setup

      - name: Build
        run: make common PLATFORM=${{ env.PLATFORM }}

  build-linux:
    runs-on: ubuntu-24.04-arm
    env:
      PLATFORM: desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-image-dev libsdl2-ttf-dev 
          sudo apt-get install -y libzip-dev liblzma-dev libzstd-dev libbz2-dev zlib1g-dev

      - name: Setup
        run: make setup

      - name: Build
        run: make common PLATFORM=${{ env.PLATFORM }}
